### ISSUE TITLE
Add tracking events

### ISSUE THREAD

**Issue by cyaiox** [decentraland/sdk#1074]
Add the following tracking events:

- [x] Keywords used to Search items
- [x] Lock/Unlock entity
- [x] Hide/Show entity
