### ISSUE TITLE
Backend-for-frontend for Explorer

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#180]
## Abstract

To remove cross-team dependencies and therefore, to enable faster iteration cycles and better software, an explorer-specific replacement for Lambdas is proposed, a brand new backend for frontend (BFF). The replacement server would live in the catalysts, and will also host a static version of Decentraland.

## Need
As the explorer (kernel+unity+sdk) grows in complexity and use cases, the servers that support that growth lag behind in terms of capabilities. Based on information of changes to the API of lambdas, very few changes have been merged during the past year. Instead, to support new use cases, third party APIs are used (opensea, quests) and many use cases are sent to the backlog depending on whether or not it depends on a server change (explore v2).

There are other problems worth mentioning in relation to the current APIs used by the explorer:
- There is no standardized way to encapsulate and proxy third party API requests to prevent CORS errors and the security of the tokens (OpenSea, Ethereum RPC calls for L1/L2)
- The API is public and that requires long-term support of endpoints even though those may not be in use by our servers anymore (Lambdas)
- HTTP concurrency defaults in browsers limit the amount of parallel requests. Creating an adversarial situation between content downloads and API calls
- The schemas used by the Lambdas endpoints differ a lot from the canonical schemas used in storage and by the ones needed by the kernel/renderer (wearables content files structures)
- Request times are capped to 30s in browsers, which is problematic for cases depending on subgraphs in which answers may take more than 30s to respond. The custom RPC protocol removes this limitation, even though it is not a good user experience, at least it won’t fail.

## Approach
The approach proposes a brand new server to replace the existing lambdas endpoints. The server would fall into the SDK team umbrella to enable rapid iterations and fixes without generating dependencies on other teams.

- The server would implement an RPC protocol using protocol buffers and https://github.com/decentraland/rpc.
- The specification of the protocol would live in a separate repository to act as an AntiCorruptionLayer (ACL), the ACL would use the [proto-compatibility-tool](https://github.com/well-known-components/proto-compatibility-tool) to ensure backward compatibility
Both the server and kernel would use [protoc-gen-dcl](https://github.com/decentraland/protoc-gen-dcl) to generate client/server code of the protocol.
- The server would serve static assets with proper caching headers to make Decentraland Web work.
- The server would connect with other servers of the same kind (horizontal scaling) using a message bus (preferably NATS) to share messages in cases like: native realm-based pub/sub

The server will start living inside the Catalyst Nodes, as part of the docker-compose bundle. In the future, it may be possible to separate and scale this service independently. But for clarity’s sake, it will start being 1-1 to catalysts.

### Multiplexed requests
Due to the multiplexed nature of the proposed RPC over WebSocket solution, requests to ask for profiles, ownership endpoints, Ethereum RPC-calls, infura or OpenSea requests can be multiplexed and canalyzed over a single transport. Leaving all the concurrent HTTP limitations free to be used by the renderer.
### Security of tokens
As of today, tokens for RPC providers and OpenSea are hardcoded into the compiled kernel. That not only leaks the keys to the public, it also makes it more difficult to upgrade since a change requires deploying a new version.
### API Flexibility
The protocol implementation would be auto generated out of protocol-buffers services definitions making it easy to add new endpoints (procedures) as needed.
### CLI Compatibility and backport
The server would be used inside the CLI, reusing the same code of the service as a library to guarantee maximum compatibility with the running version of the kernel and CLI and to reduce the amount of copied code/moving parts required to make the Decentraland explorer work.
Real time, two way communication between the server and the explorer
Services like “comms signaling” can be embedded inside the server described in this document. Even naive implementations of a simple “comms” service through the RPC can be set in place for cases like the CLI’s. Since the chat and signaling are bound to the realm and there is at least one server per realm, many responsibilities now handled by the lighthouse can be managed by this server.

### Cornerstone for new comms
Since the signaling can be handled by this server, and assuming that the server connects with others using NATS, archipelago and a super-node could be connected to this server and this server could handle all the messaging required for the system to work.
Competition (alternatives)
Two alternatives should be considered before making this decision:
Continue investing on Lambdas using HTTP and independent comms servers
Using other protocols rather than our custom RPC
Creating the server anyways, continue deprecating lambdas but using HTTP APIs instead of any RPC

---

- [x] Create new repository for bff
  - [x] Add CI/CD to that service
  - [x] Include the service in test catalysts
- [x] Create adaptation code for kernel
- [x] Assess a bunch of use cases and research final RPC protocol
- [ ] Serve the explorer from the BFF
  - [ ] Serve static files from WKC
  - [x] Backport this to the CLI

**Comment by hugoArregui** [comment]
This needs to be converted to an RFC so we can link it to it from ADR-81 and others

**Comment by menduz** [comment]
This idea was withdrawn
