### ISSUE TITLE
Enabling standalone portable experiences

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#192]
May be used for onboarding tutorials, expending machines, etc.

Open questions

- [x] Where are standalone PX deployed? -> SDK content server / Worlds
- [x] Who can create standalone PXs? -> Allow list / NAME owners
- [x] What are the required permissions needed to create a standalone PX? -> Owning a NAME
- [x] What are the required permissions needed to spawn a standalone PX? -> None
