### ISSUE TITLE
ECS 7

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#235]
- [ ] Define serialization protocol for CRDT messages **@lean/@gon**
    - [ ] Create serializers/deserializers in ECS **@lean**
        - [ ] Test in JS that lifecycle of components (put/delete) works E2E in new ECS (Jest) **@gon**
        - [ ] Broadcast messages over the wire (WS/memory) and test integration of messages (CRDT consistency) **@gon**
    - [ ] Create new components in ECS to be used by Unity (Code gen) **@lean**
        - [ ] Generate code for serialization/deserialization in TS **@lean**
    - [ ] Create new components in Unity to be used with new ECS (Transform) **@pato**
        - [ ] _First create new components, later migrate old components to newer ones_
        - [ ] New stateless components (DisposableComponents no longer exists, i.e. BoxShape, Texture) **@pato**
        - [ ] Parenting using new transform **@pato**
    
    - [ ] Integrate unity with new CRDT protocol
        - [ ] Define memory model for C# interop (ByteArray memory access, no C++ malloc) **@pato**
        - [ ] Define serialization protocol for CRDT messages **@lean/@pato**
            - [ ] Generate code for serialization/deserialization in C# **@lean/@pato**
            - [ ] Read CRDT messages
                - [ ] Implement CRDT consensus rules (timestamp, entity_id, component_id) **@gon/@pato**
                - [ ] Test E2E message parsing and entities consistency **@gon/@pato**
            - [ ] Write CRDT messages
                - [ ] Serialize state of the scene in a CRDT file
                - [ ] (start DCL editor and Builder migration)
- [ ] Do we send every entity and component using CRDT messages?
- [ ] How do we serialize components?
    - [ ] Custom/Transform components needs to be custom serializer/deserializer
    - [ ] Other components may be protobuffer/flatbuffers
        - [ ] **@lean** to test flatbuffers in TS
        - [ ] **@pato** to test flatbuffers in C#
        - [ ] Open question: are flatbuffers backwards compatible in case of removal of a field? if not, what is the path to be taken?
