### ISSUE TITLE
ECS 7 - Serialization & CRDT Development

### ISSUE THREAD

**Issue by leanmendoza** [decentraland/sdk#252]
- [x] #236
    - [x] Create serializers/deserializers in ECS **@leanmendoza**
        - [x] #237 
        - [x] Broadcast messages over the wire (WS/memory) and test integration of messages (CRDT consistency) **@gonpombo8**
    - [x] #241
        - [x] #240
        - [x] #242
        - [ ] _First create new components, later migrate old components to newer ones_
        - [x] #251
        - [x] #243
    
    - [x] #247
        - [x] #245
        - [x] #246
            - [x] #248
            - [x] Read CRDT messages
                - [x] #244
                - [x] #249
            - [ ] Write CRDT messages
                - [ ] #250
                - [ ] # (start DCL editor and Builder migration)
    - [x] #307
    - [x] #308
- [ ] #253
- [x] #254
- [x] #255
