### ISSUE TITLE
New comms v3

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#268]
New comms checklist. Please add elements here as checklist or linked issues, this issue's progression will be used to track the progress of the OKR.

#### Research
- [x] Understand and document hard & soft limitations of different WebRTC solutions for rooms
  - [x] PoC livekit
  - [ ] PoC Pion
- [x] Understand and document NATS as message bus for catalyst services
  - [ ] Setup testing NATS instances
#### Kernel
  - [x] https://github.com/decentraland/kernel/pull/260
  - [x] decentraland/kernel#264
  - [x] https://github.com/decentraland/kernel/pull/261
  - [ ] Fix realm selection algorithm to consider multiple comms protocols
  - [ ] #271
  - [x] https://github.com/decentraland/comms-v3/issues/5
  - [ ] https://github.com/decentraland/kernel/pull/269
#### Explorer BFF
  - [x] Configure BFF and CI/CD https://explorer-bff.decentraland.io https://github.com/decentraland/explorer-bff
  - [ ] Create code interfaces for BFF and write components for current Catalyst to enable slow migration
  - [ ] Connect multiple BFF "simple comms" over NATS
  - [x] https://github.com/decentraland/explorer-bff/issues/11
  - [x] https://github.com/decentraland/explorer-bff/issues/12
#### Platform 
- [x] https://github.com/decentraland/comms-v3/issues/2
- [x] https://github.com/decentraland/archipelago-service/issues/5
- [x] https://github.com/decentraland/archipelago-service/issues/12
- [x] https://github.com/decentraland/archipelago-service/issues/13
- [x] https://github.com/decentraland/archipelago-service/issues/8
- [x] https://github.com/decentraland/archipelago-service/issues/9
- [x] https://github.com/decentraland/catalyst-owner/pull/116
