### ISSUE TITLE
Benchmark new ECS vs old ECS

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#288]
To track the performance of the new ECS and to early detect regressions, we aim to have a continuous measurable benchmarking tool that compares similar programs written in the ECS6 and ECS7

The suggested approach is to create a conway's game of life, that runs an iteration every 10 updates. In those 10 updates, cells that die or born will change their size, material, shape using systems to have a good worst case scenario of several entities being updated per frame.

- [x] Create game of life using ECS6 (https://github.com/decentraland-scenes/conway-game-of-life)
- [ ] Run the scene using Node.js runtime
- [ ] Measure every update delta time, std dev and percentiles
- [ ] Measure initial memory and final memory using v8 metrics
- [ ] Create same game of life using ECS7
- [ ] Repeat measurements

Please extend this task list as needed.

**Comment by gonpombo8** [comment]
FYI, maybe this it gives you some insight on how to use/test the new ecs :) 
https://github.com/decentraland/ecs/blob/main/test/performance.spec.ts
