### ISSUE TITLE
Implement RPC Host for C# compatible with `@dcl/rpc`

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#321]
Implement RPC Host for C# compatible with `@dcl/rpc`

- [x] Define and document data structures of the protocol
- [x] Define and document the sequence diagrams of the message registration and request/responses
- [x] Create WebSocketServerTransport for C#
- [x] Implement C# `@dcl/rpc` protocol
- [x] Implement C# code generation for Host
- [x] Optimize code
- - [x] UniTask / Tasks (UniTask is Unity tasks with almost zero allocation)
- - [x] Optimize copies and conversions of byte structs
- [x] Create Unity Memory transport for TS (8MB buffer)
- [x] Create Unity Memory transport for C# (8MB buffer)
- [x] Test a lot
- [ ] Merge PR's
