### ISSUE TITLE
Increase options for interacting

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/sdk#36]
https://docs.google.com/document/d/1vK7D8bbx2U-ZZ-5iILlFn4WYwvFQlQ_x-BwB9mrDQH4/edit#heading=h.g1uhsmsys485

- [x]  Button events for more keys
- [x]  OnHover event (in-world)
- [ ]  OnHover UI event
- [ ]  Support on UI elements for Pointer UP events
- [ ]  Mouse wheel event
