### ISSUE TITLE
Preview servers tracking issue

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#462]
- [ ] https://github.com/decentraland/adr/pull/92
- [ ] Deploy a server that can hold scenes
- [ ] Make sure a proper comms schema works for that server (add to ADR)
- [ ] Mini map can be hidden (add to ADR)
- [ ] Skybox is configurable (add to ADR)
- [ ] Scene loading can be shut down (add to ADR)
- [ ] When exiting genesis city is loaded & default minimap & sky settings are restored (add to ADR)
- [ ] A deployment can be loaded at the beginning (Onboarding tutuorial)
- [ ] Metrics&Track events are sent using the identifier for the deployed scene

**Comment by menduz** [comment]
closing in favor of unified tracking issue
