### ISSUE TITLE
SDK7 Visual Tests

### ISSUE THREAD

**Issue by pravusjif** [decentraland/sdk#616]
### Tasks
- [ ] Core Testing Logic
- [ ] Test Case: Test Scene with all components
- [ ] Test Case: Test Scene with all UI Components
- [ ] Test Case: Test Scene with different Material settings
- [ ] Test Case: GLTFContainer
