### ISSUE TITLE
Implement User-Friendly Error Messaging

### ISSUE THREAD

**Issue by gonpombo8** [decentraland/sdk#855]
## Description:

Our application currently lacks a system for providing informative and user-friendly error messages. Without such a system, users can find themselves at a loss when something goes wrong. This can lead to frustration and potential abandonment of our application.

## Tasks:

- [ ] Move all the dataLayer rpc calls to their own saga, and handle the exepctions with a UI Message
- [ ] Add error handling for external resources such as Assets Catalog
- [ ] handle unexpected typescript errors

**Comment by nearnshaw** [comment]
@gonpombo8  can we consider this issue closed?
